[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.155.2"
  HUGO_ENV = "production"

# (opzionale) Forza /admin -> /admin/ (evita 404 se qualcuno digita senza slash)
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
  force = true
