[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.155.2"
  HUGO_ENV = "production"

# SOLO ADMIN - NIENTE SEO
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true